env:
  global:
    secure: NGqueWme7FGume4ZGrggdLhf1SIkbjni6BphEI0wkXPGYYD+CAQ36/XqadfI1OhJ3ZJgdqcFABJMntdzyGSI3z1SoWc7xgzMEHeW0QusOVBwJMWgMvh/DzXvp8nTG2BmVIhqzqyWVBCqzMARLNh3NnYaJFGnN2uXyXBSBh+K6ps=
language: rust
script:
  - cargo build --verbose
  - cargo test --verbose
after_success:
  - test "${TRAVIS_PULL_REQUEST}" == 'false' && test "${TRAVIS_BRANCH}" == 'master' && bash ./ci/upload-rustdoc.sh "${TRAVIS_REPO_SLUG}" "${GH_TOKEN}"
