branches:
  except:
    - gh-pages

platform:
  - x86
  - x64
environment:
  matrix:
    - RUST_INSTALL_TRIPLE: i686-pc-windows-gnu
      RUST_INSTALL_DIR: C:\Program Files (x86)\Rust
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-gnu
      RUST_INSTALL_DIR: C:\Program Files\Rust

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-$Env:RUST_INSTALL_TRIPLE.exe"
  - cmd: rust-nightly-%RUST_INSTALL_TRIPLE%.exe /VERYSILENT /NORESTART /COMPONENTS="rust,gcc,cargo" /DIR="%RUST_INSTALL_DIR%"
  - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin
  - rustc --version
  - cargo --version

build: false
test_script:
  - cargo build --verbose
  - cargo test --verbose
