install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - ps: Start-FileDownload 'https://static.rust-lang.org/cargo-dist/cargo-nightly-i686-pc-windows-gnu.tar.gz'
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - 7z e cargo-nightly-i686-pc-windows-gnu.tar.gz
  - 7z x cargo-nightly-i686-pc-windows-gnu.tar
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;%CD%\cargo-nightly-i686-pc-windows-gnu\bin
  - rustc -V
  - cargo -V
build: false
test_script:
  - cargo build --verbose
  - cargo test --verbose
